### ISSUE TITLE
Zone not found, use search

### ISSUE THREAD

**Issue by hawk4n6** [dschoeffm/hetzner-dns-certbot#2]
In same cases the requested zone could not be found. Adding the search command to both zones request in both files does solve the problem. Sample:

"https://dns.hetzner.com/api/v1/zones?search_name=${CERTBOT_DOMAIN}"

**Comment by dschoeffm** [comment]
Can you give examples of cases which don't work? If you have code, which works in your case, please feel free to fork the project and open a merge request.

**Comment by hawk4n6** [comment]
Having a bigger number of Zones the API won't find the request Domain name, curl will get an empty answer. You can increase the number of shown Zones by using "per_page=NUMBER" or, IMO more usefull, directly search for the requested Domain name, which is faster and send less data.
Working code as shown above, just add search_name (or maybe per_page=NUMBER) to the Zone request.

**Comment by dschoeffm** [comment]
I just committed the changes you proposed. It worked fine in my tests. Thank you for your feedback.
If you can confirm, that this version works in your infrastructure, please close the issue. In case something broke, please leave a comment.

**Comment by hawk4n6** [comment]
Thank you, works perfect! Very usefull scripts.
